site_name: DIAN

site_url: https://kfcaio.github.io/wiki-dian

theme:
  custom_dir: overrides
  favicon: images/favicon.png
  logo: assets/logo.png
  name: material
  language: pt
  palette:
    primary: green

extra:
  social:
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/projetodian
    - icon: fontawesome/brands/facebook
      link: https://web.facebook.com/projetodian/

markdown_extensions:
  - attr_list

strict: true

nav:
 - Home: 'index.md'
 - Sobre: 'sobre.md'
 - Membros: 'membros.md'
 - Participe: 'participe.md'
 - Encontros: 'encontros.md'
 - Artigos:
    - D.I.A.N., projeto sobre direitos animais e sustentabilidade, e as repercussões em seus integrantes: 'artigos/artigo_0.md'